import { chromium } from 'playwright';
import { execSync } from 'node:child_process';
const env = { ...process.env, DATABASE_URL: 'postgres://postgres@localhost:55432/cohort_live?sslmode=disable', NEXT_PUBLIC_SITE_URL: 'http://localhost:3301' };
const out = execSync('node scripts/create-admin.js admin@fgcu.edu "Cole Gadell"', { cwd: '/home/user/nyx-site', env }).toString();
const link = out.match(/(http:\/\/\S+verify\?token=\S+)/)[1];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1280, height: 1080 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto(link, { waitUntil: 'domcontentloaded' }).catch(() => {});
await p.goto('http://localhost:3301/admin', { waitUntil: 'networkidle' });
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/claude-0/-home-user-nyx-site/cfe83968-2fac-5ae4-b9f9-4d19863d8163/scratchpad/shots/30-live-admin.png' });
await b.close();
console.log('captured');
